name: Expose Port 8000

on:
  push:
    branches:
      - main

jobs:
  expose_port:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print Public IP
        run: |
          curl ifconfig.me

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run uvicorn
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10 # Sleep for 10 seconds to allow uvicorn to start
          ngrok http 8000 -log=stdout > ngrok.log & # Expose port 8000 using ngrok
          sleep 3600 # Sleep for 1 hour
