name: Run and Expose Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # choose the Python version you need

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Fetch public IP
      run: |
        PUBLIC_IP=$(curl ifconfig.me)
        echo "Public IP: $PUBLIC_IP"

    - name: Print local IP
      run: |
        LOCAL_IP=$(hostname -I | cut -d' ' -f1)
        echo "Local IP: $LOCAL_IP"

    - name: Expose to LocalTunnel and Run uvicorn
      run: |
        npm install -g localtunnel
        (lt --port 8000 &) && (uvicorn main:app --host 0.0.0.0 --port 8000 &) && (sleep 3600)
